export enum STATION_STATE {
    ENABLED = "ENABLED" ,
    DISABLED = "DISABLED",
    IN_APPROVAL = "IN_APPROVAL",
    REJECTED = "REJECTED"
}



export enum ENUM_CONNECTION_PROTOCOL {
    LORAWAN = "LORAWAN - JSON CIFRADO",
    NATIVE_WIFI = "NATIVE WIFI"
}