export enum STATION_STATE {
    ENABLED = "ENABLED" ,
    DISABLED = "DISABLED",
    IN_APPROVAL = "IN_APPROVAL"
}



export enum ENUM_CONNECTION_PROTOCOL {
    LORAWAN = "LORAWAN - JSON CIFRADO",
    NATIVE_WIFI = "NATIVE WIFI"
}